#!/usr/bin/python
###
# Current cost plugin
#
# This is a munin plugin to extract values from the Current Cost EnviR meter.
#
# Link this as currentcost_watts_[sensor_id] or currentcost_temp_[sensor_id]
# replacing [sensor_id] with the number of the sensor you want to monitor (0 to 8).
#
# Will read data from /tmp/__currentcost_watt_[sensor_id] and 
# /tmp/__currentcost_temp_[sensor_id] files.
# 
# @author Marcus Povey <marcus@marcus-povey.co.uk>
# @copyright Marcus Povey 2013
# @contributor Ermanno Baschiera 2014 <ebaschiera@gmail.com>
# @link http://www.marcus-povey.co.uk
# 
# Copyright (c) 2013 Marcus Povey
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
###

import sys
import os

def main(argv):
	
	watt_file = '/tmp/__currentcost_watt_'
	temp_file = '/tmp/__currentcost_temp_'
	command = argv[0].split('_')

	available_sensors = ["0", "1", "2", "3", "4", "5", "6", "7", "8"]
	
	if command[2] in available_sensors:
		requested_sensor = command[2]
	else:
		sys.exit()

	# Which mode?
	if command[1] == 'watts':
			
		# Is this a config mode?
		if len(argv) > 1 and argv[1] == 'config':
			# CONFIG
			if os.path.isfile(watt_file + requested_sensor):
				print 'graph_args --base 1000 -l 0' 
				print 'graph_scale no'
				print 'graph_title Current Cost Energy Sensor ' + requested_sensor
				print 'graph_vlabel Power in Watts'
				print 'graph_category Power'
				print 'watts.label Watts'
				sys.exit()
			
		with open(watt_file + requested_sensor) as f: s = f.read()
	        print 'watts.value ' + s
		
	elif command[1] == 'temp':
		
		# Is this a config mode?
		if len(argv) > 1 and argv[1] == 'config':
			# CONFIG
			if os.path.isfile(temp_file + requested_sensor):
				print 'graph_args --base 1000 -l -10' 
				print 'graph_scale no'
				print 'graph_title Current Cost Temperature Sensor ' + requested_sensor
				print 'graph_vlabel Temperature C'
				print 'graph_category Power'
				print 'temp.label Temperature'
				sys.exit()
			
		with open(temp_file + requested_sensor) as f: s = f.read()
	        print 'temp.value ' + s

if __name__ == "__main__":
    sys.exit(main(sys.argv))
